# Narrow compatibility adapter verified against the original Mojang client bytecode.
# MCP SRG names: https://maven.minecraftforge.net/de/oceanlabs/mcp/mcp/1.12.2/mcp-1.12.2-srg.zip
# Friendly names: https://maven.minecraftforge.net/de/oceanlabs/mcp/mcp_stable/39-1.12/mcp_stable-39-1.12.zip
# No game classes are redistributed. See legacy-adapter-1.12.2-evidence.txt in tests.
clientSha1=0f275bc1547d01fa5f56ba34bdc87d981ee12daf
minecraft=bib
instance=z
screen=m
title=blr
scheduler=a
load=a
levelSource=g
settingsType=amx
levelList=b
levelExists=f
levelId=a
levelName=b
